version: '3.5'
services:
  article_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8080"
    depends_on:
      - article_db

  article_db:
    image: mysql:8.0.19
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "publiceditor"
      MYSQL_USER: "MysqlUpdateUser"
      MYSQL_PASSWORD: "TheQuickBrownFox!!123"
