version: '3.5'
services:
  article_server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8888:8080"
    depends_on:
      - article_db

  article_db:
    build:
      context: .
      dockerfile: docker/Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "CLoTbYDEmdNbfSxb"
      MYSQL_DATABASE: "publiceditor"
      MYSQL_USER: "MysqlUpdateUser"
      MYSQL_PASSWORD: "TheQuickBrownFox!!123"
